In [13]:
#EXERCISE:

#Apply the KNeighborsClassifier to the iris dataset. Play with different values of the n_neighbors and observe how training and test score change.

In [1]:
from sklearn.datasets import load_iris

iris = load_iris()
X, y = iris.data, iris.target

iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
X, y = iris.data, iris.target
X
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
from sklearn.model_selection import train_test_split

train_X, test_X, train_y, test_y = train_test_split(X, y, 
                                                    train_size=0.8,
                                                    test_size=0.2,
                                                    random_state=123,
                                                    stratify=y)

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [41]:
classifier = KNeighborsClassifier(n_neighbors=5)

In [42]:
classifier.fit(train_X, train_y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [43]:
prediction = classifier.predict(test_X)

In [44]:
print(prediction)
print(test_y)

[1 0 2 2 0 0 2 2 2 0 0 2 2 1 2 1 0 0 0 0 0 2 2 1 2 2 1 1 1 1]
[1 0 2 2 0 0 2 1 2 0 0 1 2 1 2 1 0 0 0 0 0 2 2 1 2 2 1 1 1 1]


In [45]:
classifier.score(test_X, test_y)

0.9333333333333333

In [46]:
classifier.score(train_X, train_y)

0.9833333333333333

In [70]:
#Exercise
#The same workflow can be used for regression. In this case we want create a linear regression model using the Boston housing dataset.The Boston Housing Dataset consists of price of houses in various places in Boston. Alongside with price, the dataset also provide information such as Crime (CRIM), areas of non-retail business in the town (INDUS), the age of people who own the house (AGE)

#Import the boston dataset

import sklearn.datasets as datasets
boston = datasets.load_boston()
boston

#Insepect the boston dataset, including the keys, feature names and the description
type(boston)
boston.keys()
#boston['data']
#boston['feature_names']
#boston['DESCR']

X, y = datasets.load_boston(return_X_y=True)
print(X.shape)
type(X)

type(y)
X.size
#y.size

#Read the data into a pandas dataframe
import pandas as pd
pandas_df_X = pd.DataFrame(data=X[0:,0:],    # values
            index=range(1,507),    
            columns=boston['feature_names'])

pandas_df_X

#Split the data into training and validation data

target = np.array(boston.feature_names) == "DIS"

X = boston.data[:, np.logical_not(target)]
y = boston.data[:, target].squeeze()

X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    train_size=0.8,
                                                    random_state=1)


#Fit a linear regression to the training data
from sklearn.linear_model import LinearRegression
from sklearn import metrics

regressor = LinearRegression()  
regressor.fit(X_train, y_train) #training the algorithm

y_pred = regressor.predict(X_test)

df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df1 = df.head(25)
df1

#Validate your model

#print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
#print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
#print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
regressor.score(X_test, y_test)
regressor.score(X_train, y_train)

(506, 13)
[5.2698559  5.99664495 4.05219855 5.93608664 1.65700754 2.09865379
 7.99164618 3.33538125 2.79351467 4.14462955 2.91769819 6.50992495
 3.69909321 7.94332689 3.2033669  1.97644172 1.91320202 2.95397815
 7.58446633 1.06105258 3.53914336 0.6903276  3.10209227 4.58102237
 8.0175908  2.13747309 3.55078501 4.8704573  2.80102119 2.02760043
 7.10442174 5.39471027 7.67108887 1.57088627 4.93107732 4.08545175
 1.67153232 4.49933264 2.30890246 2.81558612 5.1706687  4.74246943
 3.51164852 2.5936263  2.25149533 2.15630008 1.20447046 1.86433704
 1.94130879 3.68232018 2.68617387 5.59770799 4.57095292 1.83796798
 2.24544509 5.16824934 2.52821472 3.86589902 3.77014358 3.30685082
 1.55564103 4.49808149 1.9769203  2.72345822 5.606716   4.21885878
 3.19485679 3.92095622 4.34598401 2.00976028 4.84025237 1.9767647
 2.19887602 3.45060435 3.69300837 3.96810661 1.70781051 6.9654804
 0.284509   7.76314248 2.13451479 3.21486663 5.93368176 1.7091451
 6.36772987 7.5775576  1.7573315  5.09615092 3.53872065

0.7624188258774383