In [2]:
pwd

'/home/suny/EAGLE-Master/second-semester/spatial-python/session-3/Spatial-Python-2020-Homework'

In [5]:
import os
os.getcwd()

'/home/suny/EAGLE-Master/second-semester/spatial-python/session-3/Spatial-Python-2020-Homework'

In [11]:
#Exercise 6
#Q1:
import numpy as np
# create a null vector of size 10
n=np.zeros(10,dtype=int)
print(n)
type(n)

#Q2: Create a random sorted vector of size 10????
np.random.seed(65)
x = np.random.choice(["Day","Night","Midnight"], size=10)
x

#Q3: Create a 3x3 matrix with values ranging from 0 to 8
# 2d array
b = np.array([[0, 1, 2],[3,4,5],[6, 7, 8]])
print(b)
print(type(b))
print(np.shape(b))

#Q4: Create a 5x5 array with 2 on the border and 0 inside
# two by two matrix of zeros
zero_three_by_three = np.zeros(shape=(5,5),dtype=int)
print(zero_three_by_three)
#
two_vector = np.full((1,5),2)  # Create a constant array
two_vector_col=np.array([2,2,2])

zero_three_by_three[0,:]=two_vector
zero_three_by_three[4,:]=two_vector
zero_three_by_three[1:4,0]=two_vector_col
zero_three_by_three[1:4,4]=two_vector_col
print(zero_three_by_three)

#Q5:

r = np.arange(0,2)
#print(r)
t = np.flip(r)
#print(t)
w_type_one=np.array([r,r,r,r])
print(w_type_one)

t = np.flip(r)
w_type_two=np.array([t,t,t,t])
print(w_type_two)


w_sample=np.array([w_type_one,w_type_two]).reshape(1,2,8)
print(w_sample)
np.shape(w_sample)
print("****************************")
w_sample_row=np.array([w_sample,w_sample,w_sample,w_sample]).reshape(1,8,8)
print(w_sample_row)
np.shape(w_sample_row)

#Q6:
#Create a random array and subtract the mean of each row of a matrix
e = np.array(range(9)).reshape(1,3,3)  # Create an array filled with random values
print(e)   

# mean along the axis = 0  
mean_row= np.mean(e, axis =2, dtype='int')
#print(mean_row)


e2 = np.append( mean_row, mean_row, axis = 1 )
#print(e2)
e3 = np.append( e2, mean_row, axis = 1 )
#print(e3)
z = e3.reshape( 3 , 3 )
mean_matrix = z.transpose() 
print(mean_matrix)

print(e-mean_matrix)


#Q7: Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinate
import math
print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
cartesian_coord=np.random.random((10,2))
print(cartesian_coord)

#calculate radius
cartes_power=pow(cartesian_coord,2)
radius_arr=np.ones((10,1),dtype=float)
for i in range(len(radius_arr)):
    radius_arr[i,0]=np.sqrt(cartes_power[i,0]+cartes_power[i,1])
#print(radius_arr)

#calculate angle(in degrees)
degree_arr=np.ones((10,1),dtype=float)
for j in range(len(degree_arr)):
    degree_arr[j,0]=np.degrees(math.atan(cartesian_coord[j,1]/cartesian_coord[j,0]))

#print(degree_arr)


polar_coord=np.hstack((radius_arr, degree_arr))
print(polar_coord)

print("*******************************")

#Q8: Consider a random vector with shape (100,2) representing coordinates, find point by point distances

import numpy as np
a= np.random.random((100,2))
x,y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)        


[0 0 0 0 0 0 0 0 0 0]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
<class 'numpy.ndarray'>
(3, 3)
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[2 2 2 2 2]
 [2 0 0 0 2]
 [2 0 0 0 2]
 [2 0 0 0 2]
 [2 2 2 2 2]]
[[0 1]
 [0 1]
 [0 1]
 [0 1]]
[[1 0]
 [1 0]
 [1 0]
 [1 0]]
[[[0 1 0 1 0 1 0 1]
  [1 0 1 0 1 0 1 0]]]
****************************
[[[0 1 0 1 0 1 0 1]
  [1 0 1 0 1 0 1 0]
  [0 1 0 1 0 1 0 1]
  [1 0 1 0 1 0 1 0]
  [0 1 0 1 0 1 0 1]
  [1 0 1 0 1 0 1 0]
  [0 1 0 1 0 1 0 1]
  [1 0 1 0 1 0 1 0]]]
[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
[[1 1 1]
 [4 4 4]
 [7 7 7]]
[[[-1  0  1]
  [-1  0  1]
  [-1  0  1]]]
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
[[0.69931375 0.77151083]
 [0.51455245 0.23580689]
 [0.23003963 0.50571517]
 [0.13418496 0.56146226]
 [0.4820002  0.67966876]
 [0.73870729 0.16514066]
 [0.10069371 0.92758757]
 [0.22027153 0.10020807]
 [0.79305629 0.10742643]
 [0.45574091 0.10711613]]
[[ 1.04128223 47.81017222]
 [ 0.56601158 24.6208363 ]
 [ 0.55557723 65.54016966]
 [ 0.57727418 76.55889041]
 [ 

In [11]:
#Exercise 7

#Q1:Import GlobalLandTemperaturesByMajorCity.csv
import os
import numpy as np
import pandas as pd

data = './Data/non-spatial/GlobalLandTemperatures/GlobalLandTemperaturesByMajorCity.csv'
df = pd.read_csv(data, sep=',')
df

#Q2:Look at the first five entries
l=df[:5]
print(l)

#Q3:Print the name of all the columns
print(df.columns )
print("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")

#Q4:What is the number of observations in the dataset?
print(len(df))


#Q5:Display a summary of the basic information about this DataFrame and its data
print(df.head())              # show data head
df.tail()
df['Country'].value_counts()  # Count number of rows with each unique value of variable
df['City'].value_counts()
df['AverageTemperature'].mean()
df['AverageTemperature'].median()


#Q6:Select just the 'AverageTemperature' and 'City' columns from the DataFrame

print("*****************************************************")
cols = [1,3]
df_new = df[df.columns[cols]]
print(df_new)

#Q7:Count the number of cities in the dataset
print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
df['City'].value_counts()

#?Q8:Calculate the mean temperature for each city over all years. Sort the values in the 'AverageTemperature' - in decending order
print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
df_city_temp=df.groupby(['City'])['AverageTemperature'].mean().sort_values(ascending=False)
print(len(df_city_temp))
print(df_city_temp[:25])#show the first 25 cities


#Q9:Calculate the maximal AverageTemperature in european cities between 1990 and 2013
print("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^")
#slice based on country names
df_europe_range = df.loc[(df['Country'] == 'Germany') |  
                (df['Country'] == 'Belgium') | (df['Country'] =='Bulgaria') | (df['Country'] == 'Croatia')|
                (df['Country'] == 'Cyprus') |(df['Country'] == 'Czech Republic') | (df['Country'] == 'Denmark') | (df['Country']=='Estonia') | (df['Country']=='Finland') |
                (df['Country'] == 'France') | (df['Country'] == 'Austria') | (df['Country'] == 'Greece') | (df['Country']=='Hungary') | (df['Country']=='Ireland') | (df['Country']=='Italy') |
                (df['Country'] == 'Latvia') | (df['Country'] == 'Lithuania') | (df['Country'] == 'Luxembourg') | (df['Country']=='Malta') | (df['Country']=='Netherlands') |
                (df['Country'] == 'Poland') | (df['Country'] == 'Portugal') | (df['Country'] == 'Romania ') | (df['Country']=='Slovakia') | (df['Country']=='Slovenia') | (df['Country']=='Spain') |
                (df['Country'] == 'Sweden') & (df['dt'] >= '1990-01-01') & (df['dt'] < '2014-01-01')] 
           

#print(df_europe_range.head())    
#type(df_europe_range)

#slice based on latitude and longitude range
#df_europe_range = df.loc[(df['Latitude'] >= '40.00N') & (df['Latitude'] <= '70.00N' ) & 
#                         (df['Longitude'] <= '40.00E') & (df['Longitude'] <= '10.00W' )
#                         & (df['dt'] >= '1990-01-01') & (df['dt'] < '2014-01-01')] 
           

print(df_europe_range.head())    
print(len(df_europe_range))



max_temp_europ=df_europe_range['AverageTemperature'].max()
type(max_temp_europ)
print(max_temp_europ)

           dt  AverageTemperature  AverageTemperatureUncertainty     City  \
0  1849-01-01              26.704                          1.435  Abidjan   
1  1849-02-01              27.434                          1.362  Abidjan   
2  1849-03-01              28.101                          1.612  Abidjan   
3  1849-04-01              26.140                          1.387  Abidjan   
4  1849-05-01              25.427                          1.200  Abidjan   

         Country Latitude Longitude  
0  Côte D'Ivoire    5.63N     3.23W  
1  Côte D'Ivoire    5.63N     3.23W  
2  Côte D'Ivoire    5.63N     3.23W  
3  Côte D'Ivoire    5.63N     3.23W  
4  Côte D'Ivoire    5.63N     3.23W  
Index(['dt', 'AverageTemperature', 'AverageTemperatureUncertainty', 'City',
       'Country', 'Latitude', 'Longitude'],
      dtype='object')
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
239177
           dt  AverageTemperature  AverageTemperatureUncertainty     City  \
0  1849-01-01              26.

In [39]:
#Exercise 8
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
import seaborn as sns
global_temp=pd.read_csv('./SpatialPython2020/Data/non-spatial/GlobalLandTemperatures/GlobalLandTemperaturesByMajorCity.csv')


# ????Q1:Calculate the mean temperature (all cities) for each year plot the data
# Average temp by year
#global_temp['dt'] = pd.to_datetime(global_temp['dt'])

# Set the datetime column as the index
#global_temp.index = global_temp['dt'] 
#global_temp=global_temp.groupby([global_temp.index.year])['AverageTemperature','AverageTemperatureUncertainty'].mean().reset_index()
#print(global_temp)




#Q2:Calculate the mean temperature of german cities for each year (between 1990 and 2013). 
#Create a plot with 4 graphs each showing the mean temperature for one season (spring, summer, autumn, winter) per year

df_german_range = global_temp.loc[(global_temp['Country'] == 'Germany') & (global_temp['dt'] >= '1990-01-01') & (global_temp['dt'] < '1991-01-01')] #& (df['dt'] < '2014-01-01')
df_german_range.head() 
#Winter
df_german_winter = global_temp.loc[(global_temp['Country'] == 'Germany') & (global_temp['dt'] >= '1990-01-01') & (global_temp['dt'] < '1990-03-21')]
df_german_winter.head()
#Spring
df_german_spring = global_temp.loc[(global_temp['Country'] == 'Germany') & (global_temp['dt'] >= '1990-03-21') & (global_temp['dt'] < '1990-06-21')]
df_german_spring.head()
#sns.set(style="darkgrid")
#plt.figure(figsize=(16, 10))
#sns.lineplot(x='dt', y="AverageTemperature", hue='City' ,data=df_german_range, palette="coolwarm")

# Q3:Calculate the temperature difference for each city in 2010
# and create a barplot showing the ranked temperature difference



ModuleNotFoundError: No module named 'seaborn'

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
#import seaborn as sns
#!pwd
global_temp=pd.read_csv('./Data/non-spatial/GlobalLandTemperatures/GlobalLandTemperaturesByMajorCity.csv')
#global_temp.tail()
#global_temp.head()
#print(len(global_temp))

global_temp['year'] = pd.DatetimeIndex(global_temp['dt']).year
temp_grouped = global_temp.groupby(['City']).agg({'AverageTemperature': ['mean']})
temp_grouped.columns = ['temp_mean']
temp_grouped = temp_grouped.reset_index()
print(len(temp_grouped))
print(len(global_temp['dt']))
# ????Q1:Calculate the mean temperature (all cities) for each year plot the data
# Average temp by year
#global_temp['dt'] = pd.to_datetime(global_temp['dt'])

# Set the datetime column as the index
#global_temp.index = global_temp['dt'] 
#global_temp=global_temp.groupby([global_temp.index.year])['AverageTemperature','AverageTemperatureUncertainty'].mean().reset_index()
#print(global_temp)



100
239177
